sudo: false

language: python

python:
  - "2.7"

branches:
  only:
    - master

before_script:
  - pip install sphinx

script:
#  - cd source
  - sphinx-build -b html source html
  - ls
  - pwd
deploy:
  provider: pages
  repo: karpovichart/karpovichart.github.io
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: test
  local_dir: html