sudo: false

language: python

python:
  - "2.7"

branches:
  only:
    - master

before_script:
  - pip install sphinx

script:
  - sphinx-build -b html source ./
  - ll
#deploy:
#  provider: pages
#  repo: karpovichart/karpovichart.github.io
#  skip_cleanup: true
#  github_token: $GITHUB_TOKEN
#  keep_history: true
#  local_dir: html/
#  target_branch: master
#  on:
#    branch: master